layout_spectrum: 0.5635858759426023
typography_spectrum: 0.02256392875188353
color:
  brandStrength: 0.3502378255110418
  lightness: 0.4942044206794425
  saturation: 0.5633684921483187
  rhythmicContrast: 0.22931457840920527
  brandColors:
    - '#332532'
    - '#644D52'
    - '#F77A52'
    - '#FF974F'
    - '#A49A87'
name: Elephant Orange Design
title: ''
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/4c94f722-6a61-4028-8103-b6756c358178.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/4c94f722-6a61-4028-8103-b6756c358178.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: ''
purpose:
  - type: contact
    url: 'mailto:joelamothe@gmail.com'
    label: CONTACT ME
  - type: internal
    label: PAST WORK
    item: c296d5eb-4bc1-44bf-af3f-37a091def180
github: true
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1e209ca7-72ed-4840-9e0b-b8f1045f8cb6.jpg
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/54f3224e-a383-4deb-92b3-ae74321481d7.jpg
author:
  name: Joseph Michael Lamothe
  email: joelamothe@gmail.com
opengraph:
  appId: elephantorangedesign
  type: Graphic Design
analytics:
  twitter: ''
