typography_spectrum: 0.11844778749621519
color:
  brandStrength: 0.3574564630884935
  lightness: 0.49797480351918627
  saturation: 0.5665528872690284
  rhythmicContrast: 0.976408749069871
  brandColors:
    - '#332532'
    - '#644D52'
    - '#F77A52'
    - '#FF974F'
    - '#A49A87'
github: true
opengraph:
  appId: elephantorangedesign
  type: Graphic Design
layout_spectrum: 0.7479982918249166
analytics:
  twitter: ''
author:
  name: Joseph Michael Lamothe
  email: joelamothe@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/61866974-6bfc-4efd-b2fe-443be6cb3e4f.jpg
name: Elephant Orange Design
navigation:
  - name: T-Shirt Designs
    id: 721a23e9-5ca9-48fc-b683-4d895ef85b2c
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1e209ca7-72ed-4840-9e0b-b8f1045f8cb6.jpg
title: ''
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/4c94f722-6a61-4028-8103-b6756c358178.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/4c94f722-6a61-4028-8103-b6756c358178.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: ''
purpose:
  - type: contact
    url: 'mailto:joelamothe@gmail.com'
    label: CONTACT ME
  - type: internal
    label: PAST WORK
    item: c296d5eb-4bc1-44bf-af3f-37a091def180
content_rating:
  adult: false
